name: Build and Push RecSys Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'recsys.docker/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker build variables
        id: docker_vars
        run: |
          # Extract ARG values from Dockerfile (assuming they are on single lines)
          CUDA_VERSION=$(grep -m 1 '^ARG CUDA_VERSION=' recsys.docker/Dockerfile | cut -d'=' -f2)
          CUDNN_VERSION=$(grep -m 1 '^ARG CUDNN_VERSION=' recsys.docker/Dockerfile | cut -d'=' -f2)
          UBUNTU_VERSION=$(grep -m 1 '^ARG UBUNTU_VERSION=' recsys.docker/Dockerfile | cut -d'=' -f2)
          PYTHON_VERSION=$(grep -m 1 '^ARG PYTHON_VERSION=' recsys.docker/Dockerfile | cut -d'=' -f2)

          echo "CUDA_VERSION=${CUDA_VERSION}" >> $GITHUB_ENV
          echo "CUDNN_VERSION=${CUDNN_VERSION}" >> $GITHUB_ENV
          echo "UBUNTU_VERSION=${UBUNTU_VERSION}" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> $GITHUB_ENV

          echo "Extracted Dockerfile ARGs:"
          echo "  CUDA_VERSION: ${CUDA_VERSION}"
          echo "  CUDNN_VERSION: ${CUDNN_VERSION}"
          echo "  UBUNTU_VERSION: ${UBUNTU_VERSION}"
          echo "  PYTHON_VERSION: ${PYTHON_VERSION}"

      - name: Build and push RecSys Base Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./recsys.docker
          file: ./recsys.docker/Dockerfile.base
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/recsys/base:latest
            ghcr.io/${{ github.repository_owner }}/recsys/base:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/recsys/base:cuda${{ env.CUDA_VERSION }}-cudnn${{ env.CUDNN_VERSION }}-ubuntu${{ env.UBUNTU_VERSION }}-py${{ env.PYTHON_VERSION }}
          build-args: |
            CUDA_VERSION=${{ env.CUDA_VERSION }}
            CUDNN_VERSION=${{ env.CUDNN_VERSION }}
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}

      - name: Build and push RecSys Full Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./recsys.docker
          file: ./recsys.docker/Dockerfile.full
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/recsys/full:latest
            ghcr.io/${{ github.repository_owner }}/recsys/full:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/recsys/full:cuda${{ env.CUDA_VERSION }}-cudnn${{ env.CUDNN_VERSION }}-ubuntu${{ env.UBUNTU_VERSION }}-py${{ env.PYTHON_VERSION }}
          build-args: |
            CUDA_VERSION=${{ env.CUDA_VERSION }}
            CUDNN_VERSION=${{ env.CUDNN_VERSION }}
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
